kubernetes/spire/Chart.yaml, kubernetes/spire/templates/server/networkpolicy.yaml
This fixes the network policy so that cray-bss can talk to spire-tokens properly.  The version is being bumped in this because the fix needs to be released today so it's included in the next CSM 1.2 alpha.
* Partially Resolves [CASMTRIAGE-2730](https://connect.us.cray.com/jira/browse/CASMTRIAGE-2730)
* wasp
I validated this change by using curl in the cray-bss pod to verify that it could access the spire-token service. I also verified that a different pod, keycloak-postgres-0, could not access it.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Were continuous integration tests run? If not, why? N, there are no tests for this chart that are run in Jenkins
- Was downgrade tested? If …
=> CASMTRIAGE-2730 Fix network policy

kubernetes/spire/Chart.yaml, kubernetes/spire/templates/agent/deployment.yaml, kubernetes/spire/templates/agent/psp.yaml, kubernetes/spire/templates/jwks/deployment.yaml, kubernetes/spire/templates/server/deployment.yaml, kubernetes/spire/values.yaml
This changes the user and group that runs spire containers from root to 65534 (nobody). It requires an init job to change who owns the hostPaths so that the spire-agent and spire-server can still write to the directory. hostPaths are required due to how spire talks using sockets. There's work being done by the spire team to get rid of this requirement, however it's not currently usable.
The version is being bumped in this chart because it will be released after being merged in so that it can get into the latest CSM-1.2 Alpha.
* Resolves [CASMPET-5178](https://connect.us.cray.com/jira/browse/CASMPET-5178)
Validated that the default user in each container was nobody and that services were being run as the nobody user. 
- Were the install/upgrade-based validation …
=> CASMPET-5178 Run containers as nobody

kubernetes/spire/Chart.yaml, kubernetes/spire/values.yaml
This disabled the xname workloads by default. We won't be enabling them by default until we're sure it will work without a performance hit. The version is being bumped as this will be released as soon as it's merged.
* Resolves [CASMPET-5187](https://connect.us.cray.com/jira/browse/CASMINST-5187)
The enable/disable was tested when the option was added and a retest to disable the functionality is not needed.
None
=> CASMPET-5187 Disable xname workloads by default

kubernetes/spire/Chart.yaml, kubernetes/spire/templates/agent/configuration.yaml, kubernetes/spire/templates/agent/deployment.yaml, kubernetes/spire/templates/agent/psp.yaml
spire-jwks was failing because the spire-agent pod was no longer able to
start properly. This updates the configuration and readds the HostPID
option so that spire-agent functions properly.
The version is being bumped because this change is needed asap.
* Resolves [CASMTRIAGE-2791](https://connect.us.cray.com/jira/browse/CASMTRIAGE-2791)
* 
* hela
Validated spire-jwks returned the proper keys instead of "document not available".
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? Y
- Were continuous integration tests run? If not, why? N/A
- Was downgrade tested? If not, why? N, …
=> CASMTRIAGE-2791 Fix spire-agent pod

charts/spire/CHANGELOG.md, charts/spire/Chart.yaml
Use new cray-service base chart which includes the latest pgbouncer master-19 image. Increased the 
chart major version from 1.x to 2.0, as the base cray-service chart also contains an increased major
version from 7.x to 8.x.
* Resolves [CASMPET-5202]
* Merge with/before/after `https://github.com/Cray-HPE/base-charts/pull/34`
* `wasp`
Tested the new chart on wasp, and verified that the spire-postgres-pooler pods successfully
pulled the latest pgbouncer image. Pod logs showed no errors after being up for more than
30 minutes.
- Were continuous integration tests run? If not, why?
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) …
=> Fixes CASMPET-5202: use new cray-service for latest pgbouncer

charts/spire/Chart.yaml, charts/spire/templates/server/networkpolicy.yaml
The spire-server pods need to be able to talk to each other on port
54440. If they can't then the script that setups spire on storage nodes
will fail 2 out of 3 requests.
* Resolves [CASMINST-3916](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3916)
* surtur
Verified that spire-token requests from the spire-registration-server container always succeeded after the upgrade was pushed and that no side effects occurred from the upgrade.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N/A
- Was downgrade tested? If not, why? N, not needed.
=> CASMINST-3916 Fix spire network policy

LICENSE, charts/.snyk, charts/spire/Chart.yaml, charts/spire/templates/jwks/deployment.yaml, charts/spire/templates/patch-pooler-affinity-hook.yaml, charts/spire/values.yaml
The spire-jwks pods could all be running on the same node, and if
that goes down then spire-jwks is not available and this causes
requests through the API gateway to fail due to the auth check in
OPA to fail.
The proposed fix is to set pod-antiaffinity for spire-jwks so that
the pods will not all wind up on the same node.
Upgrades were hitting problems when all of the pooler pods wound
up on the same node. While the postgres operator is enhanced to
set the anti-affinity on the pooler deployment it's not smart
enough to update the deployment if it already exists. This adds
a post-upgrade hook that just updates the deployment with the
same settings that the postgres operator would set if it created
the deployment.
IS THIS A NEW FEATURE OR CRITICAL BUG FIX? bug fix
DOES THIS CHANGE INVOLVE …
=> CASMINST-3917 / CASMINST-3919

charts/spire/CHANGELOG.md, charts/spire/Chart.yaml
Bump spire chart patch version from 2.3.0 to 2.3.1, so that the dependent pgbouncer patch version (8.1.2) can be picked up and rebuilt for the spire chart.
* Resolves [CASMINST-4082]
* `mug`
Tested the new chart on mug, and verified that the spire-postgres-pooler pods successfully pulled the latest pgbouncer image. Pod logs showed no errors after being up for more than 15 minutes.
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
Low. The pgbouncer version upgrade was a patch version upgrade.
=> CASMINST-4082: bump spire version to 2.3.1

.gitignore, charts/spire-intermediate/Chart.yaml, charts/spire-intermediate/templates/clusterrole.yaml, charts/spire-intermediate/templates/cronjob.yaml, charts/spire-intermediate/values.yaml
This adds support for checking to see if the existing spire CA certificate is less than a month old and replace it with a new one if it is. This is done via a cronjob that's run once a week. The existing job is kept so that the spire CA can be created upon first install.
* Resolves [CASMPET-5082](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5082) 
Validated that the certificate was updated properly when the conditions were met. Also validated that the cert was created correctly when it didn't already exist and that it wasn't touched when it wasn't ready to be updated.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N/A
- …
=> CASMPET-5082 Update image and cronjob

charts/spire/CHANGELOG.md, charts/spire/Chart.yaml, charts/spire/templates/agent/deployment.yaml, charts/spire/templates/server/deployment.yaml, charts/spire/tests/kuttl/deployments/02-assert.yaml, charts/spire/tests/kuttl/deployments/04-assert.yaml, charts/spire/tests/kuttl/values.yaml, charts/spire/values.yaml
This PR uses updated images (spire-tokens & wait-for-it) for CVE remediation with automated rebuild.
* Resolves [CASMINST-4505](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4505)
Upgraded spire chart; validated that it uses the new images, and ncn-join-tokens are generated correctly.
- Were continuous integration tests run? If not, why?
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) created for this change?
Low.
=> CASMINST-4505: use updated images for CVE remediation

charts/spire/Chart.yaml, charts/spire/templates/server/configuration.yaml, charts/spire/templates/server/workloads.yaml
The BOS reporter creates a symlink on the compute nodes called
/usr/bin/bos-reporter-spire-agent. The Spire OPA rules uses the name
/usr/bin/bos-state-reporter-spire-agent. These need to match, so I'm
changing the Spire name to be called /usr/bin/bos-reporter-spire-agent.
CASMCMS-7987
* Hela
I made the following manual changes on Hela:
I changed the configmaps for  opa-policy-ingressgateway and  spire-workloads to reflect the proper names.
I then restarted cray-opa-ingressgateway deployment and the spire-server stateful sets.
I installed a new RPM on the compute node that had the correct name change as well.
After doing all of this, the BOS client freshly installed on the compute node could communicate with the BOS components …
=> CASMCMS-7987: Resolve name mismatch

charts/.snyk, charts/spire/Chart.yaml, charts/spire/kind.yaml, charts/spire/templates/bundle/deployment.yaml, charts/spire/templates/jwks/deployment.yaml, charts/spire/templates/patch-pooler-affinity-hook.yaml, charts/spire/templates/server/deployment.yaml, charts/spire/tests/kuttl/deployments/02-assert.yaml, charts/spire/tests/kuttl/deployments/03-assert.yaml
Change pod affinity from preferred to required. If these pods all end up scheduled on the same node then when that node goes down so does the API gateway.
* Resolves [CASMINST-4734](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4734)
Validated that the podAffinity policies were changed to requiredDuringSchedulingIgnoredDuringExecution.
- Was upgrade tested? Y
- Was downgrade tested? Y
None
=> CASMINST-4734 Change pod affinity to required

charts/spire/Chart.yaml, charts/spire/templates/jwks/virtualservice.yaml, charts/spire/values.yaml
This reverts the change done in CASMINST-3979. This fixes an issue where the opa pods were failing to properly cache spire-jwks requests, causing port exhaustion which breaks the ingress gateways after a few minutes.
* Resolves [CASMTRIAGE-3616](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3616)
* shandy
validated that connections from opa to spire-jwks no longer ran out of ports.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? Y
- Was downgrade tested? If not, why? N, downgrade is broken.
This exposes the JWKS public keys. However, these are only useful to validate JWTs …
=> CASMTRIAGE-3616 Revert CASMINST-3979

.github/workflows/charts-lint-test-scan.yml, charts/.snyk, charts/spire/Chart.yaml, charts/spire/templates/ncn/configuration.yaml, charts/spire/templates/ncn/deployment.yaml, charts/spire/templates/psp/psp.yaml, charts/spire/values.yaml
This fixes two issues:
- request-ncn-join-token fails to configure spire-agent on CSM 1.3 nodes due to the spire root path changing
- Add a vshasta flag that fixes the issue where request-ncn-join-token failed to request a join_token for vshasta nodes.
* Resolves [CASMTRIAGE-3714](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3714)
Validated the paths changed and that setting `vshasta: true` allowed the request-ncn-join-token pod to configure spire-agent on vshasta nodes.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Was upgrade tested? If …
=> CASMTRIAGE-3714 Fix request-ncn-join-token for CSM 1.3

charts/spire/Chart.yaml, charts/spire/templates/server/configuration.yaml, charts/spire/templates/server/workloads.yaml
heartbeat is now using spire tokens by default. This adds heartbeat workloads for storage nodes.
* Resolves [CASMPET-5835](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5835)
* `fanta`
Validated that storage nodes started heartbeating properly.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? Y
- Was downgrade tested? If not, why? N
- Were new tests (or test issues/Jiras) created for this change? Y
- [] Copyrights updated
=> CASMPET-5835 Add heartbeat to storage node

charts/spire/Chart.yaml
Use the new base chart to include the new postgres-db-backup image for CVE remediation.
* Partially Resolves [CASMPET-5873](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5873)
* Future work required by [CASMPET-5873](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5873)
Updated the spire chart to use the new base chart, made sure spire used the updated cray-postgres-db-backup image, and its db backup job completed with no errors.
- Were continuous integration tests run? If not, why?
- Was …
=> CASMPET-5873: use new base chart for CVE fix

charts/spire/Chart.yaml
Rebuilds spire to pickup base chart cray-service:8.2.3
Bugfix
* Resolves [CASMPET-5961](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5961)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
vshasta
* `<development system>`
```
$ kubectl get cronjob spire-postgresql-db-backup -n spire -o yaml | grep cray-service
helm.sh/base-chart: cray-service-8.2.3
$ kubectl get cronjob spire-postgresql-db-backup -n spire -o yaml | grep backup | grep image
image: …
```
=> CASMPET-5961-1.3 : Rebuild spire to pick up cray-service:8.2.3

charts/spire/CHANGELOG.md, charts/spire/Chart.yaml
Use cray-postgres-db-backup:0.2.3 image to fix postgres db restore issue that was caused by incompatible sql version in previous images.
* Resolves [CASMPET-5966](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5966)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
* `<development system>`
_How were the changes tested and success verified? If schema changes were part of this change, how were those …
=> CASMPET-5966: use cray-postgres-db-backup:0.2.3 image

charts/spire/Chart.yaml, charts/spire/templates/ncn/deployment.yaml
This adds error checking to the request-ncn-join-token pods. The pods will now error out if it fails 6 times (30 seconds). This should allow them to restart if the istio-proxy sidecar isn't working.
* Resolves [CASMINST-5650](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5650) 
* mug
- Were continuous integration tests run? If not, why? Y 
- Was downgrade tested? If not, why? Y
=> CASMINST-5650 Add error checking to ncn tokens pod

Makefile
Fix for artifactory authentication.
* Resolves [CASMINST-5738](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5738)
Jenkins succeeds and publishes charts
* Jenkins
Build pipeline
K=Low
=> CASMINST-5738: Use local helm config to inherit auth for csm-helm-charts

charts/spire/Chart.yaml, charts/spire/values.yaml
the reference to alpine no longer validates in the csm repo. The full path needs to be specified.
* Partially Resolves [CASMPET-5081](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5081)
Used kuttl to validate that chart could be installed with the paths provided.
- Was upgrade tested? If not, why? N, not needed
- Was downgrade tested? If not, why? N, not needed
=> CASMPET-5081 Fix alpine image reference

charts/spire/Chart.yaml, charts/spire/templates/ncn/deployment.yaml, charts/spire/templates/server/configuration.yaml, charts/spire/templates/server/workloads.yaml
This adds new paths to allow the migration of spire-agent binaries from /usr/bin to /opt/cray/cray-spire.
* Resolves [CASMPET-6193](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6193)
These changes were cherry picked from the master branch.
- Was downgrade tested? If not, why? N
- Were new tests (or test issues/Jiras) created for this change? Y
This needs additional testing on bare metal machines to validate that the changes work with SKERN changes.
=> CASMPET-6193 Add new spire-agent bin paths

charts/spire/Chart.yaml, charts/spire/templates/ncn/deployment.yaml
The latest version of the spire-agent RPM locks down the /var/lib/spire/conf directory, breaking the request-ncn-join-token pod. This fixes the issue, allowing NCNs to be joined to spire.
* Resolves [CASMTRIAGE-4857](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4857)
* fanta
validated new chart fixed the issue and that NCNs were properly joined to spire.
- Was downgrade tested? If not, why? N
=> CASMTRIAGE-4857 Fix permission issue with conf dir

Makefile
The `-3` option in helm unittest has been removed and is breaking the build. This removes the option, allowing it to complete.
=> Remove obsolete option for helm unittest

Jenkinsfile.github, Makefile, charts/cray-spire/Chart.yaml, charts/cray-spire/values.yaml
This bumps the spire version to 1.5.5 so that it matches the version of spire-agent being deployed in Cheshire Cat.
* Resolves [CASMPET-6421](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6421)
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Was upgrade tested? If not, why? N, No environment available.
- Was downgrade tested? If not, why? N, No environment available. …
=> CASMPET-6421 Bump cray-spire version to 1.5.5

charts/cray-spire/Chart.yaml, charts/cray-spire/templates/update-bss/job.yaml
This adds a backoff to the update-bss job and adds a 15 second timer to its curl command. This should allow it to complete properly when run from our csm test pipeline.
* Resolves [CASMPET-6447](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6447)
* drax
Generated the job template using helm template and applied it on drax with some minor modifications so it worked with the existing spire install.
- Was upgrade tested? If not, why? N, no environment available
- Was downgrade tested? If not, why? N, no environment available
Limited testing was done due to the lack of …
=> CASMPET-6447 Add backoff and timeout to update-bss job

charts/cray-spire/Chart.yaml, charts/cray-spire/templates/ncn/deployment.yaml, charts/cray-spire/templates/server/networkpolicy.yaml, charts/cray-spire/templates/update-bss/job.yaml
- Fixed incorrect namespace in cray-spire networkpolicy
- Fixed /tokens path permission issues between request-ncn-join-token and spire-agent 1.5.5
- Increased the time spire-update-bss will take to attempt to update BSS and how long it keeps the job pods around.
* Resolves [CASMPET-6447](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6447)
* yasha
Validated Charts changes fixed the issue on yasha
- Was upgrade tested? If not, why? N
- Was downgrade tested? If not, why? N …
=> CASMPET-6447 Fix broken integration tests take 3

charts/spire/Chart.yaml, charts/spire/templates/update-bss/job.yaml
This job is causing test failures due to BSS failing to come up before its retries are exceeded. This updates those retries to fix this issue.
* Resolves [CASMPET-6439](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6439)
Back ports a change that was tested in the 1.5 testing pipeline.
- Was upgrade tested? If not, why? N/A
- Was downgrade tested? If not, why? N/A
_Are there known issues with these changes? Any other …
=> CASMPET-6439 Increase update-bss job retries

charts/cray-spire/Chart.yaml, charts/cray-spire/values.yaml, charts/spire/Chart.yaml, charts/spire/values.yaml
Restoring a day old backup will break most of the spire-agents due to restoring outdated authentication information. The proper way to recover is to reinstall the spire helm charts, rejoin NCNs, and restart all UAN and compute nodes.
=> CASMPET-6580 Disable postgres backups

charts/cray-spire/Chart.yaml, charts/cray-spire/templates/agent/psp.yaml, charts/cray-spire/templates/psp/psp.yaml, charts/cray-spire/templates/server/deployment.yaml
The hostPath has changed for this chart. However, the PSP was not updated along with this path change, causing the spire-jwks service to fail to start. This fixes the permission issue.
=> CASMPET-6615 Add new spire paths to PSP

charts/cray-spire/Chart.yaml, charts/cray-spire/values.yaml
disableExternalCerts should only be used during testing and should not be set as a default.
=> CASMTRIAGE-5750 Fix cray-spire TLS failure

charts/spire/Chart.yaml
This adds the ability to override the default postgresql connection pooler resources.
=> CASMPET-6720 Update cray-service to 8.2.4

charts/cray-spire/Chart.yaml, charts/cray-spire/templates/update-bss/job.yaml
Extends the TTL of the update-bss job to 1 month if there are delays on the installation process. This allows for installation to be done over a weekend or week if there are some issues getting through the install in one step.
* Resolves [CASMTRIAGE-6625](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6625)
* mug
* vidar
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? y
- Were continuous integration tests run? If not, why? y
- Was upgrade tested? If not, why? y
- Was downgrade tested? If not, why? y
- Were new tests (or test issues/Jiras) created for this change? y
No risk just extending the TTL on a job.
=> CASMTRIAGE-6625: Update TTL for update-bss job

charts/cray-spire/Chart.yaml, charts/cray-spire/templates/server/configuration.yaml, charts/cray-spire/templates/server/workloads.yaml
sbps-marshal workload needs to be added to spire-server and
cray-spire-server pods on NCN nodes
sbps-marshal workload which is iSCSI based boot content projection service needs to be added to spire and cray-spire. 
Testing is done by adding the entries for sbps-marshal workload into spire and cray-spire manually. Detailed steps are in CASMPET-6799. The same needs to be tested using the CSM latest builds once this code is in.
* Mug
Testing is done by adding sbps-marshal workload to spire and cray-spire manually. Detailed steps are listed in the CASMPET-6799.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N/A
- Were continuous integration tests run? If not, why? - N/A 
- Was upgrade tested? If not, why? - N/A 
- Was downgrade tested? If …
=> CASMPET-6799: Add SBPS Marshal Spire Workload on NCN

charts/cray-spire/Chart.yaml, charts/cray-spire/templates/server/workloads.yaml, charts/spire/Chart.yaml, charts/spire/templates/server/workloads.yaml
Fixes a missed keyword in the workload definition in the new dvs mqtt workload. This lead to spire having two workloads on xname enabled systems one non xname and one with xnames. This lead to the token received first to be the non xname enabled token which failed in the validation on the mqtt broker.
* Resolves [CASMPET-7113](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7113)
*  lemondrop
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? y
- Were continuous integration tests run? If not, why? y
- Was upgrade tested? If not, why? y
- Was downgrade tested? If not, why? y
- Were new tests …
=> CASMPET-7113: Update DVS-mqtt workload definition for Xname validation

charts/cray-spire/Chart.yaml, charts/cray-spire/templates/ncn/deployment.yaml, charts/cray-spire/values.yaml, charts/spire/Chart.yaml, charts/spire/templates/ncn/deployment.yaml, charts/spire/values.yaml
Update spire and cray-spire charts for k8s 1.24.
These changes include
- adding 'node-role.kubernetes.io/control-plane' toleration
- using container image docker-kubectl:1.24.17
* Resolves [CASMPET-7081](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7081)
* Resolves [CASMPET-7082](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7082)
Upgraded both charts on Beau. I saw that new toleration was present in 'request-ncn-join-token' pods.
Low risk.
=> CASMPET-7081 add 'node-role.kubernetes.io/control-plane' toleration for k8s 1.24

charts/spire-intermediate/Chart.yaml, charts/spire-intermediate/templates/cronjob.yaml
CronJob apiVersion `batch/v1` has been around since k8s 1.21. CronJob apiVersion `batch/v1beta1` is deprecated in K8s 1.25+. Use `batch/v1` in prep for K8s upgrade to 1.32.
* Resolves [CASMPET-7373](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7373)
Installed chart with changes on `molly` successfully.
```
pit:~/studenym/spire-intermediate # helm install -n vault spire-intermediate .
NAME: spire-intermediate
LAST DEPLOYED: Thu Feb  6 19:44:58 2025
NAMESPACE: vault
STATUS: deployed
REVISION: 1
TEST SUITE: None
pit:~/studenym/spire-intermediate # kubectl get cronjob -n vault
NAME                 SCHEDULE    TIMEZONE   SUSPEND   ACTIVE   LAST SCHEDULE   AGE
spire-intermediate   0 0 * * 1   <none>     False     0        <none>          8s
tpm-intermediate     0 0 * * 1   <none>     False …
```
=> CASMPET-7373: Use apiVersion 'batch/v1' in spire-intermediate cronjob.yaml template

charts/cray-spire/Chart.yaml, charts/cray-spire/templates/server/workloads.yaml
This fixes a bug in the indentation of a workload in workloads.yaml. This bug prevented systems with xname validation enabled from getting tokens for workloads
* Resolves [CASMTRIAGE-7880](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7880)
* lemondrop
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? y
- Were continuous integration tests run? If not, why? y
- Was upgrade tested? If not, why? y
- Was downgrade tested? If not, why? y
- Were new tests (or test issues/Jiras) created for this change? y
no risk
=> CASMTRIAGE-7880: Fix indentation issue in workloads.yaml

charts/cray-spire/Chart.yaml, charts/cray-spire/templates/jwks/deployment.yaml, charts/cray-spire/templates/jwks/serviceaccount.yaml
Re-add the spire jwks service account. This fixes a bug where the spire server is unable to properly target jwks pods, because the server config is using the following selector: `k8s:sa:{{ include "spire.fullname" . }}-jwks`.
Whereas currently, the jwks pods are using the default service account, which breaks the `Validate token key ID exists in cray-spire jwks` goss test (and presumably a bunch of other things, too).
We decided to use a dedicated service account, instead of updating the spire server config, to avoid potential unexpected RBAC scope increases on the default service account.
* Resolves [CASMTRIAGE-7898](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7898)
* Change will also be needed in CSM, `release/1.7`.
* `molly`
* `wasp`
I manually upgraded `cray-spire` to this …
=> CASMTRIAGE-7898: fix jwks service account

charts/cray-spire/Chart.yaml, charts/cray-spire/values.yaml
- Fixes: [CASMPET-6937](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6937)
- Bugfix Pull Request
This changes the log level on spire-agent to WARN. This was chosen because of the amount of logs that the spire-agent gives can cause slowdowns on larger systems. On all internal systems the log messages for info are not needed and provide no helpful data. 
Tested on tyr by changing the loglevel on the config file and restarting the service to ensure it started up.
There is no risk as this can be changed on the fly for systems if we need more logging for some reason, however it has never been useful logging to begin with.
=> CASMPET-6937: Update the spire-agent default log level to WARN

charts/cray-spire/Chart.yaml, charts/cray-spire/templates/server/workloads.yaml
There is a bug where when xname validation is enabled some workloads that need extra long TTLs are changed to have standard TTL. This is incorrect and needed to be addressed.
* Resolves [CASMTRIAGE-8192](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-8192)
* lemondrop
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?y
- Were continuous integration tests run? If not, why?y
- Was upgrade tested? If not, why?y
- Was downgrade tested? If not, why?y
- Were new tests (or test issues/Jiras) created for this change?y
No risks this is correcting xname validation workloads to what they are in non xname validation workloads.
=> CASMTRIAGE-8192: Update TTLs for ckdump_helper workload

charts/cray-spire/Chart.yaml, charts/cray-spire/templates/ncn/deployment.yaml
This fixes a bug where if the ncns have been converted to use TPM for node attestation and then the request-join-ncn pods are restarted it wipes away the new spire config. This also makes it so the tpm enabled nodes do not even get a token to improve security for TPM enabled nodes.
* Resolves [CASMPET-7531](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7531)
* mug
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? y
- Were continuous integration tests run? If not, why? y
- Was upgrade tested? If not, why? y
- Was downgrade tested? If not, why? y
- Were new tests (or test issues/Jiras) created for this change? y
This takes away risk of generating a join token for each node while TPM node attestation is enabled. There is a risk that a node …
=> CASMPET-7531: Update request-ncn-join daemonset to respect TPM enablement
